#import <libxml2/libxml/tree.h>
#import <libxml2/libxml/parser.h>
#import <libxml2/libxml/HTMLtree.h>
#import <libxml2/libxml/HTMLparser.h>
#import <libxml2/libxml/xpath.h>
#import <libxml2/libxml/xpathInternals.h>
#import <libxml2/libxml/xmlerror.h>
#import <libxml2/libxml/c14n.h>
#import <libxml2/libxml/catalog.h>
#import <libxml2/libxml/chvalid.h>
#import <libxml2/libxml/debugXML.h>
#import <libxml2/libxml/nanoftp.h>
#import <libxml2/libxml/nanohttp.h>
#import <libxml2/libxml/parserInternals.h>
#import <libxml2/libxml/pattern.h>
#import <libxml2/libxml/relaxng.h>
#import <libxml2/libxml/schemasInternals.h>
#import <libxml2/libxml/schematron.h>
#import <libxml2/libxml/uri.h>
#import <libxml2/libxml/xinclude.h>
#import <libxml2/libxml/xmlmodule.h>
#import <libxml2/libxml/xmlreader.h>
#import <libxml2/libxml/xmlsave.h>
#import <libxml2/libxml/xmlschemas.h>
#import <libxml2/libxml/xmlschemastypes.h>
#import <libxml2/libxml/xmlunicode.h>
#import <libxml2/libxml/xmlwriter.h>
#import <libxml2/libxml/xpointer.h>